#!/bin/bash

vmdir=/home/nosoxon/workspace/kvm-testbed
installer="$vmdir"/archlinux-2023.01.01-x86_64.iso

ifname=kvm-testbed
mac_addr=22:38:76:06:77:f6

qemu_opts=(
	# Machine + CPU
	-machine type=q35,accel=kvm,usb=on,smm=on
	-cpu     host # ,hv_relaxed,hv_spinlocks=0x1fff,hv_vapic,hv_time (for M$ guests)
	-smp     cpus=4,sockets=1,cores=2,threads=2
	-m       12G

	# UEFI
	-global  driver=cfi.pflash01,property=secure,value=on
	-drive   if=pflash,format=raw,unit=0,file="$vmdir"/ovmf-code.fd,readonly=on
	-drive   if=pflash,format=raw,unit=1,file="$vmdir"/ovmf-vars.fd

	# Network
	-device  e1000e,id=net0,bus=pcie.0,addr=0x19.0,netdev=net0,mac=$mac_addr
	-netdev  tap,id=net0,ifname=$ifname,script="$vmdir"/ifup,downscript="$vmdir"/ifdown

	# User IO
	-device  usb-tablet
	-display gtk,gl=on

	# -daemonize # won't work if using sudo without NOPASSWD for nftables

	# Drives
	-drive id=disk0,if=virtio,cache=none,format=raw,file="$vmdir"/disk.img
	# installer
	-drive file=$installer,index=1,media=cdrom
	-boot menu=on
)

exec qemu-system-x86_64 "${qemu_opts[@]}"
